Repository GPII/universal, pull requests merged in 2020-05, with the labels that each got.

#790 GPII-3853: Analysis related metrics improvements
  gpii/node_modules/eventLog/README.md
  gpii/node_modules/eventLog/package.json
  gpii/node_modules/eventLog/src/eventLog.js
  gpii/node_modules/eventLog/src/metrics.js
  gpii/node_modules/eventLog/test/EventLogTests.js
  gpii/node_modules/eventLog/test/metricsTests.js
  gpii/node_modules/flowManager/src/FlowManager.js
Labels: 1.3.x

#869 GPII-4461: Offboarded the screen mirror solution due to instability issues
  testData/deviceReporter/acceptanceTests/win7_builtIn.json
  testData/deviceReporter/installedSolutions.json
  testData/preferences/intra_application.json5
  testData/solutions/win32.json5
  tests/JournalIntegrationTests.js
  tests/data/preferences/os_win.json5
  tests/platform/windows/windows-builtIn-testSpec.js
Labels: Morphic 1.3.5

#859 GPII-4399 Resolve paths in solutions registry entries before capturing them
  gpii/node_modules/flowManager/src/Capture.js
  gpii/node_modules/flowManager/test/CaptureTests.js
  gpii/node_modules/flowManager/test/configs/gpii.flowManager.tests.capture.fakeData.config.json5
  gpii/node_modules/flowManager/test/data/capture_solutionsRegistry.json
Labels: Important, Morphic 1.3.5, Morphic 1.4

#857 GPII-4226: Onboard the rest of JAWS 2019 settings
  gpii/node_modules/matchMakerFramework/test/data/jaws_application.json
  gpii/node_modules/matchMakerFramework/test/inverseCapabilities/jaws_application_expected.json
  gpii/node_modules/settingsHandlers/index.js
  gpii/node_modules/settingsHandlers/src/JawsSettingsHandler.js
  gpii/node_modules/settingsHandlers/src/settingsHandlerUtilities.js
  gpii/node_modules/settingsHandlers/test/JawsSettingsHandlerTests.js
  gpii/node_modules/solutionsRegistry/src/schemas/solution-schema.json5
  gpii/node_modules/solutionsRegistry/test/SolutionsRegistryFileTests.js
  gpii/node_modules/solutionsRegistry/test/ValidationMiddlewareTests.js
  gpii/node_modules/testing/src/Mocks.js
  testData/preferences/james.json5
  testData/preferences/javier.json5
  testData/preferences/jaws.json5
  testData/solutions/win32.json5
  tests/CloseConflictingAppsTests.js
  tests/data/preferences/screenreader_common.json5
  tests/platform/windows/windows-jaws-testSpec.js
Labels: Morphic 1.3.5, Morphic 1.4, onboarding

#873 GPII-4487 Disambiguating the windows desktop personalization names. O…
  testData/solutions/win32.json5
Labels: Morphic 1.3.5
